FROM amd64/ubuntu:noble

RUN apt update
RUN apt install -y tmux npm

RUN npm init -y
RUN npm install -D @playwright/test@1.54.2
RUN npx playwright install-deps
RUN npx playwright install chromium

RUN echo "current dir:"
RUN ls

WORKDIR /app
# Copy artifact
COPY backend/builds/bin/cocktail-party ./backend/builds/bin/.
COPY frontend ./frontend
COPY buildscripts/frontend-testing.sh ./buildscripts/frontend-testing.sh
COPY frontend-tests ./frontend-tests

CMD ["/bin/bash"]