FROM amd64/ubuntu:noble AS buildstage

RUN apt update
RUN apt install -y clang-18 build-essential
RUN update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100
RUN apt install -y libasio-dev

WORKDIR /app

COPY backend/src ./backend/src
COPY backend/3rdParty ./backend/3rdParty
COPY backend/project.lua ./backend/project.lua
COPY buildscripts/release.sh ./buildscripts/release.sh
COPY premake ./premake
COPY premake5.lua .

# for other stage
#COPY buildscripts/start-server.sh ./buildscripts/start-server.sh
COPY frontend ./frontend
COPY etc .

RUN buildscripts/release.sh

FROM amd64/ubuntu:noble

RUN apt update
RUN apt install -y nginx

WORKDIR /app

COPY --from=buildstage /app/backend/builds/bin/cocktail-party .
#COPY buildscripts/start-server.sh ./buildscripts/start-server.sh
COPY frontend ./frontend
COPY etc ./etc

EXPOSE 61919/tcp

CMD nginx && ./cocktail-party
#CMD ./buildscripts/start-server.sh 
#CMD ["/bin/bash"]