FROM amd64/ubuntu:noble AS buildstage

RUN apt update
RUN apt install -y llvm-18 clang-18 build-essential
RUN update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100
RUN update-alternatives --install /usr/bin/llvm-profdata llvm-profdata /usr/bin/llvm-profdata-18 100 && \
update-alternatives --install /usr/bin/llvm-cov llvm-cov /usr/bin/llvm-cov-18 100
RUN apt install -y libasio-dev

WORKDIR /app

COPY backend/src ./backend/src
COPY backend/3rdParty ./backend/3rdParty
COPY backend/project.lua ./backend/project.lua
COPY buildscripts/release.sh ./buildscripts/release.sh
COPY premake ./premake
COPY premake5.lua .

RUN buildscripts/release.sh

FROM amd64/ubuntu:noble

RUN apt update
RUN apt install -y libasio-dev nginx 
#tmux

WORKDIR /app

COPY --from=buildstage /app/backend/builds/bin/cocktail-party .
COPY buildscripts/start-server.sh ./buildscripts/start-server.sh
COPY frontend .
#COPY nginx file 

EXPOSE 61919/tcp

CMD ["./buildscripts/start-server.sh"]
