FROM amd64/ubuntu:noble

RUN apt update
RUN apt install -y tmux npm

WORKDIR /app

# Copy artifact
COPY backend/builds/bin/cocktail-party ./backend/builds/bin/.
COPY frontend ./frontend
COPY buildscripts/frontend-testing.sh ./buildscripts/frontend-testing.sh
COPY frontend-tests ./frontend-tests

CMD ["/bin/bash"]